### ISSUE TITLE
Zombie Python processes for each Duo push

### ISSUE THREAD

**Issue by codekoala** [duosecurity/duo_openvpn#14]
I'm running an OpenVPN server in an Alpine-based Docker image that includes the current Duo plugin. I've noticed that there's a zombie Python process for each auth request to the VPN server.

Here's the Dockerfile that's used to build the Docker image:

```
FROM alpine:3.4
MAINTAINER ....

RUN apk update && \
    apk add openvpn openvpn-dev gcc libc-dev curl make python

RUN cd /root && \
    curl -Lo /root/openvpn-duo.tar.gz https://github.com/duosecurity/duo_openvpn/tarball/master && \
    tar xf /root/openvpn-duo.tar.gz && \
    cd duosecurity-duo_openvpn-* && \
    make && make install

ENTRYPOINT ["/usr/sbin/openvpn"]
```

I run the container using a command similar to this: ``docker run -d --net=host -v $(pwd):/cfg alpenvpn --config /cfg/server.conf``. We can authenticate using Duo just fine, but the Python processes don't go away until the container is restarted.

```
/opt/duo # ps -A -ostat,comm
STAT COMMAND
S    openvpn
Z    python
Z    python
S    sh
Z    python
Z    python
Z    python
R    ps
```

**Comment by BradleyHiggins** [comment]
That makes sense!  Commit 792fa6373244c732d97ff69799b7739326774784 changed how the Duo OpenVPN plugin communicates with the python process it forks to execute the 2FA to Duo.  It was implemented to intentionally abandon the child process, expecting that init would clean it up.  Unfortunately, this won't work in your Docker image, because there is no init process.  I think something like https://github.com/Yelp/dumb-init may work, to run this in a container.

Thanks for using Duo!

**Comment by codekoala** [comment]
Great, thanks for the feedback! I'll try out dumb-init in the image.

**Comment by codekoala** [comment]
I have verified that using dumb-init solves the issue for me. Thanks again!
